app = "odnelazm-mcp-web"
primary_region = "fra"

[http_service]
internal_port = 8055
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"

[env]
RUST_LOG = "info"

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
